version: '3.5'
services:
  consagrado-app:
    container_name: consagrado-app
    build: .
    volumes:
      - ../../app:/go/src/github.com/little-pan-development/consagrado
    depends_on:
      - consagrado-db
    ports:
      - 8080:8080
    env_file: env
    networks:
      - consagrado-net
  consagrado-db:
    container_name: consagrado-db
    image: mysql:5.7
    volumes:
      - ../../data:/var/lib/mysql:rw
    ports:
      - 33060:3306
    restart: always
    env_file: env
    networks:
      - consagrado-net
networks:
  consagrado-net:
    driver: bridge